Repository deepforge-dev/deepforge, pull requests merged in 2020-03, with the labels that each got.

#1449 Ensure local ops decrement runningJobs & fixed pipeline term. Fix #1448
  src/plugins/ExecuteJob/ExecuteJob.js
  src/plugins/ExecutePipeline/ExecutePipeline.js
Labels: bug, pipeline execution

#1451 Update webgme version to 2.40.1. Fixes #1409
  package-lock.json
  package.json
Labels: bug

#1453 Validate node arguments in 2PC Core. Closes #1452
  src/plugins/TwoPhaseCommit/TwoPhaseCore.js
  test/unit/plugins/TwoPhaseCommit/TwoPhaseCommit.spec.js
Labels: enhancement

#1457 Pass getAttributeNames requests through. Fixes #1456
  src/plugins/TwoPhaseCommit/TwoPhaseCore.js
Labels: bug

#1461 Remove old commented out code from TwoPhaseCommit
  src/plugins/TwoPhaseCommit/TwoPhaseCore.js
Labels: minor, refactor

#1460 Update default compute backend order. Closes #1458
  config/components.json
Labels: enhancement, job execution, pipeline execution, refactor

#1459 Simplify metadata logic for job/pipeline execution. Closes #1455
  src/common/Constants.js
  src/plugins/ExecuteJob/ExecuteJob.Metadata.js
  src/plugins/ExecuteJob/ExecuteJob.js
  src/plugins/ExecuteJob/metadata/Figure.js
  src/plugins/ExecuteJob/metadata/Metadata.js
  src/plugins/ExecuteJob/metadata/index.js
  src/plugins/ExecutePipeline/ExecutePipeline.js
  src/seeds/pipeline/pipeline.webgmex
  src/seeds/pipeline/version.txt
  src/seeds/project/project.webgmex
  test/unit/plugins/ExecuteJob/ExecuteJob.spec.js
Labels: enhancement, job execution, pipeline execution, refactor

#1470 Stop propagation of click event in exec index. Fixes #1469
  src/visualizers/widgets/ExecutionIndex/ExecutionIndexWidget.js
Labels: bug, ui/ux

#1471 Add aws-sdk to sciserver compute backend. Closes #1464
  src/common/compute/backends/sciserver-compute/files/prepare-and-run.sh
Labels: compute, enhancement

#1473 Only show configurable options in log viewer. Fixes #1472
  src/visualizers/widgets/LogViewer/LogViewerWidget.js
  src/visualizers/widgets/TextEditor/TextEditorWidget.js
Labels: bug, ui/ux

#1477 Fix ace language tools path. Fixes #1476
  src/visualizers/widgets/TextEditor/TextEditorWidget.js
Labels: bug, ui/ux

#1481 Refactor constants to include reserved attrs. Closes #1480
  src/common/Constants.js
  src/common/viz/NodePrompter.js
  src/common/viz/OperationControl.js
  src/common/viz/PipelineControl.js
  src/visualizers/panels/ExecutionView/ExecutionViewControl.js
  src/visualizers/panels/OperationCodeEditor/OperationCodeEditorControl.js
  src/visualizers/panels/OperationInterfaceEditor/OperationInterfaceEditorControl.js
  src/visualizers/widgets/OperationInterfaceEditor/Buttons.js
  src/visualizers/widgets/PipelineEditor/PipelineEditorWidget.js
Labels: enhancement, refactor

#1488 Set NODE_ENV using ENV command (not inline!). Fixes #1487
  Dockerfile
Labels: bug, docker, minor

#1490 Refactored TabbedTextEditor for easier extension. Closes #1489
  src/visualizers/panels/TabbedTextEditor/TabbedTextEditorControl.js
  src/visualizers/panels/TabbedTextEditor/TabbedTextEditorPanel.js
  src/visualizers/widgets/TabbedTextEditor/TabbedTextEditorWidget.js
Labels: enhancement, refactor, ui/ux

#1492 Configurable TextEditor language, default template. Closes #1491
  src/visualizers/panels/TextEditor/TextEditorControl.js
  src/visualizers/widgets/TextEditor/TextEditorWidget.js
Labels: enhancement, minor, ui/ux

#1497 Filter *out* reserved operation attribute names. Fixes #1496
  src/common/viz/OperationControl.js
Labels: bug, custom operations

#1499 Check if attribute exists after node is loaded. Fixes #1498
  src/visualizers/panels/TextEditor/TextEditorControl.js
Labels: bug, ui/ux

#1500 Add support for defining custom operation dependencies. Closes #1478
  src/common/Constants.js
  src/plugins/GenerateJob/GenerateJob.js
  src/plugins/GenerateJob/templates/start.js
  src/seeds/pipeline/pipeline.webgmex
  src/seeds/pipeline/version.txt
  src/visualizers/Visualizers.json
  src/visualizers/panels/OperationDepEditor/OperationDepEditorPanel.js
  src/visualizers/panels/OperationDepEditor/environment.yml.tpl
  src/visualizers/panels/OperationEditor/OperationEditorPanel.js
  src/visualizers/panels/OperationSecondaryEditor/OperationSecondaryEditorControl.js
  src/visualizers/panels/OperationSecondaryEditor/OperationSecondaryEditorPanel.js
  webgme-setup.json
Labels: custom operations, enhancement

#1501 Fix typo in maintainer name.
  Dockerfile
Labels: minor, refactor

#1503 Add default config value for TabbedEditorWidget. Fixes #1502
  src/visualizers/widgets/TabbedTextEditor/TabbedTextEditorWidget.js
Labels: bug, ui/ux

#1505 Refactor library update/seed upload to async/await.
  src/plugins/ImportLibrary/ImportLibrary.js
  src/plugins/UploadSeedToBlob/UploadSeedToBlob.js
Labels: refactor

#1506 Import library as authenticated user. Fix #1504
  src/plugins/ImportLibrary/ImportLibrary.js
Labels: bug, extensions

#1508 Generate valid branch names on collision. Fixes #1507
  src/plugins/ImportLibrary/ImportLibrary.js
Labels: bug, minor

#1511 Update to node 12 (current LTS). Closes #1510
  .travis.yml
  Dockerfile
Labels: enhancement, minor

#1512 Deploy Deepforge Server Action (Closes #1482)
  .github/workflows/docker-build.yml
  docker-compose.yml
Labels: Continuous Deployment

#1519 Split environment.yml into separate server, worker env files. Closes #1518
  environment.server.yml
  environment.worker.yml
Labels: enhancement, minor

#1521 Removed references to old env file. Closes #1520
  bin/deepforge
  package.json
  utils/conda-utils.js
Labels: bug, command line interface

#1514 Add deepforge create-env command for building conda env. Close #1466
  bin/deepforge
  package.json
  test/unit/external-utils/conda-utils.spec.js
  utils/conda-utils.js
  utils/extender.js
Labels: enhancement, extensions

#1523 Remove conda-forge from default env tpl. Closes #1522
  src/visualizers/panels/OperationDepEditor/environment.yml.tpl
Labels: custom operations, enhancement, minor

#1525 Customize text editor on ctrl+right click. Closes #1524
  src/visualizers/widgets/TextEditor/TextEditorWidget.js
Labels: enhancement, minor, ui/ux

#1531 Add Conda.export to conda utils. Closes #1530
  utils/conda-utils.js
Labels: enhancement, minor

#1535 Set config to {} if falsey (not as arg w/ default). Fixes #1534
  src/visualizers/widgets/TabbedTextEditor/TabbedTextEditorWidget.js
Labels: bug, ui/ux

#1532 Distribute the worker environment with job files. Closes #1528
  bin/deepforge
  src/plugins/GenerateJob/GenerateJob.js
  src/plugins/GenerateJob/templates/environment.worker.yml
  src/plugins/GenerateJob/templates/index.js
  src/plugins/GenerateJob/templates/start.js
Labels: compute, enhancement, extensions

#1543 Enable the default behavior for clicking checkbox. Fixes #1542
  src/visualizers/widgets/ExecutionIndex/ExecutionIndexWidget.js
Labels: bug, ui/ux

#1548 Add documentation about token_keys config. Closes #1547
  .gitignore
  config/config.production.js
  docs/deployment/native.rst
  token_keys/README.md
  utils/generate_token_keys.sh
Labels: deployment, documentation

#1546 Scatter Plots Support from Matplotlib. Closes #1394
  src/common/viz/FigureExtractor.js
  src/plugins/ExecuteJob/metadata/Figure.js
  src/plugins/GenerateJob/templates/backend_deepforge.py
  src/seeds/pipeline/pipeline.webgmex
  src/seeds/pipeline/version.txt
  src/visualizers/panels/ExecutionIndex/ExecutionIndexControl.js
  src/visualizers/panels/PlotlyGraph/PlotlyGraphControl.js
  src/visualizers/widgets/PlotlyGraph/PlotlyDescExtractor.js
Labels: job metadata

#1559 Update ecmaVersion to 2020. Closes #1558
  .eslintrc.yml
Labels: enhancement

#1557 Add additional CI checks for skipped tests. Closes #1555
  .codeclimate.yml
  .travis.yml
  package.json
  utils/additional-ci-checks.js
Labels: enhancement, testing
