Repository deepforge-dev/deepforge, pull requests merged in 2020-04, with the labels that each got.

#1562 Change Tensorflow from pypi to conda in dev deployment. Closes #1561
  .deployment/README.md
  .deployment/dev-entrypoint.sh
  .deployment/docker-compose-overrides.yml
Labels: deployment

#1564 Clear sciserver tokens before expiration. Fixes #1563
  src/common/compute/backends/sciserver-compute/Client.js
  src/common/sciserver-auth.js
  src/common/storage/backends/sciserver-files/Client.js
Labels: bug, compute, storage

#1565 Update github actions to match dockerhub repo.
  .github/workflows/docker-build.yml
Labels: minor, refactor

#1568 Update image and conda env creation. Fixes #1566
  src/common/compute/backends/sciserver-compute/Client.js
  src/common/compute/backends/sciserver-compute/files/prepare-and-run.sh
  src/plugins/GenerateJob/templates/start.js
Labels: bug, compute

#1569 Pass username/password instead of token. Fixes #1567
  src/common/compute/backends/sciserver-compute/Client.js
Labels: bug, compute

#1571 move aws sdk path to config.base.js. Fixes #1570
  config/config.base.js
  config/config.webgme.js
Labels: bug

#1560 Set the NODE_ENV to test (fix config for job build utils). Fixes #1540
  .travis.yml
  src/seeds/devProject/devProject.webgmex
  test/integration/ExecutePipeline.spec.js
Labels: testing

#1576 Add retries to storage adapter integration tests. Fixes #1575
  test/integration/StorageBackends.spec.js
Labels: bug, testing

#1577 Remove redundant statement in start.js
  src/plugins/GenerateJob/templates/start.js
Labels: minor, refactor

#1574 Remove partial trailing line before parsing metadata cmd. Fix #1573
  src/plugins/ExecuteJob/ExecuteJob.js
Labels: bug, job metadata

#1582 Only remove nodes with IDs after last cmd ID. Fixes #1581
  src/plugins/ExecuteJob/ExecuteJob.Metadata.js
Labels: bug, job execution, job feedback

#1588 Call python directly if no conda support. Fixes #1587
  src/plugins/GenerateJob/templates/start.js
Labels: bug

#1590 Update webgme version. Fixes #1580
  package-lock.json
  package.json
Labels: bug

#1592 Update project seed. Fixes #1591
  src/seeds/project/project.webgmex
Labels: bug, minor

#1595 Remove auth from heartbeat endpoint. Fixes #1594
  src/routers/ExecPulse/ExecPulse.js
Labels: bug

#1589 Refactor to use conda env name constant consistently
  src/plugins/GenerateJob/templates/start.js
Labels: job execution, minor, refactor

#1597 Move Deployment Script to the Repository (Closes #1596)
  .deployment/README.md
  .deployment/deploy-deepforge
  .deployment/docker-compose-overrides.yml
  .dockerignore
  .github/workflows/docker-build.yml
  .gitignore
Labels: deployment, enhancement, minor

#1598 Move dockerfiles to docker/ Closes #1513
  .deployment/dev-entrypoint.sh
  .github/workflows/docker-build.yml
  docker/Dockerfile
  docker/Dockerfile.kitchensink
  docker/Dockerfile.worker
  docker/docker-compose.yml
Labels: docker, minor

#1602 Update webgme version. Closes #1601
  package-lock.json
Labels: enhancement, minor

#1609 Fix Miniconda download webpage in utils/install-conda.sh
  utils/install-conda.sh
Labels: testing

#1606 Disable local compute in deployment (Closes #1605)
  .deployment/dev-entrypoint.sh
Labels: job execution

#1584 Don't hardcode the plot height. Fixes #1583
  src/visualizers/widgets/PlotlyGraph/PlotlyDescExtractor.js
Labels: bug, ui/ux

#1600 Remove --worker option from deepforge start. Closes #1599
  bin/config.json
  bin/deepforge
  bin/envConfig.json
  bin/start-worker.js
  docker/Dockerfile.worker
  package-lock.json
  package.json
  test/integration/ExecutePipeline.spec.js
  test/unit/cli/cli.spec.js
Labels: enhancement, minor

#1617 Remove old worker functions from bin/deepforge. Fixes #1616
  bin/deepforge
  package.json
Labels: bug

#1619 Disable GME storage on deployment. Closes #1618
  .deployment/dev-entrypoint.sh
Labels: continuous deployment, deployment

#1613 Updates to CLI and deployment docs. Closes #1517
  docs/deployment/dockerized.rst
  docs/deployment/native.rst
  docs/deployment/overview.rst
  docs/deployment/quick_start.rst
  docs/fundamentals/custom_operations.rst
  docs/fundamentals/integration.rst
  docs/fundamentals/operation_editor.png
  docs/fundamentals/operation_environment.png
  docs/fundamentals/operation_interface.png
  docs/fundamentals/plotloss.png
  docs/fundamentals/train_operation.png
  docs/getting_started/getting_started.rst
  docs/getting_started/hello_cifar.rst
  docs/getting_started/quick_start.rst
  docs/index.rst
  docs/reference/3d_graph.png
  docs/reference/cli.rst
  docs/reference/configuration.rst
  docs/reference/mnist_fashion.png
  docs/reference/operation_feedback.rst
Labels: documentation

#1622 Silence environment configuration commands. Fixes #1621
  src/common/compute/backends/sciserver-compute/files/prepare-and-run.sh
Labels: bug, compute, minor

#1623 Use tf from conda for worker machines. Fixes #1620
  .deployment/dev-entrypoint.sh
Labels: bug, compute, deployment

#1625 Add check to CI for deepforge extension installation. Fixes #1624
  package.json
  utils/additional-ci-checks.js
Labels: bug

#1626 Fix deployment directory and ENV variables in workflow
  .github/workflows/docker-build.yml
Labels: continuous deployment

#1628 Reword error message in SciServer Files
  src/common/storage/backends/sciserver-files/Client.js
Labels: minor, refactor

#1631 Improved server port detection in GME storage client. Fixes #1629
  src/common/storage/backends/StorageClient.js
  src/common/storage/backends/gme/Client.js
  test/unit/common/storage/backends/gme/Client.spec.js
Labels: bug, storage

#1633 More verbose error logs on data retrieval err. Closes #1632
  src/plugins/GenerateJob/templates/start.js
Labels: minor

#1644 Set correct default port when https. Fixes #1643
  src/common/storage/backends/gme/Client.js
  test/unit/common/storage/backends/gme/Client.spec.js
Labels: bug, deployment, storage

#1647 Hide sciserver password. Closes #1637
  src/common/compute/backends/sciserver-compute/metadata.json
  src/common/storage/backends/sciserver-files/metadata.json
Labels: enhancement, minor, ui/ux

#1648 Save/load previous settings in config dialog. Closes #1638
  src/common/viz/ConfigDialog.js
Labels: enhancement, ui/ux

#1651 Allow loading config with missing values. Fixes #1650
  src/common/viz/ConfigDialog.js
Labels: bug, ui/ux

#1649 Upload execution files to temporary storage. Closes #1349
  .travis.yml
  src/common/compute/backends/sciserver-compute/Client.js
  src/common/compute/backends/sciserver-compute/metadata.json
Labels: compute, enhancement

#1657 Add backwards compatibility to SciServerFiles. Fixes #1656
  src/common/storage/backends/sciserver-files/Client.js
Labels: bug, storage

#1659 Use metadata name field by default (if available). Close #1658
  src/common/viz/ConfigDialog.js
Labels: enhancement, minor, ui/ux

#1661 Ask if should delete assoc data from storage. Closes #1660
  src/common/viz/ConfirmDialog.js
  src/visualizers/panels/ArtifactIndex/ArtifactIndexControl.js
  src/visualizers/widgets/ArtifactIndex/ArtifactIndexWidget.js
Labels: enhancement, ui/ux

#1663 Remove old getSetterSchema from v1
  src/common/utils.js
Labels: minor, refactor

#1664 Encrypt auth information in the database. Closes #1653
  src/common/utils.js
  src/common/viz/ConfigDialog.js
  test/unit/common/utils.spec.js
Labels: enhancement

#1666 Uniform error handling in SciServer Files. Fixes #1665
  src/common/storage/backends/sciserver-files/Client.js
Labels: bug, minor, storage

#1667 Use correct storage client for inputs. Fixes #1662
  src/common/plugin/LocalExecutor.js
  src/plugins/ExecuteJob/ExecuteJob.js
Labels: bug, storage

#1669 Add better error logging for SciServer Files. Fixes #1668
  src/common/storage/backends/sciserver-files/Client.js
Labels: bug, storage

#1672 Fail gracefully if no saved settings. Fixes #1671
  src/common/viz/ConfigDialog.js
Labels: bug

#1677 Add support for auth detection in "group" config types. Fixes #1676
  src/common/viz/ConfigDialog.js
Labels: bug
